services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
  memcached:
    image: memcached
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4
    ports:
      - "11211:11211"
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
  nats:
    image: nats:latest
    command:
      - --jetstream
    ports:
      - "4222:4222"
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit-cachimbo"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbit-cachimbo"
